title: Pages with Jekyll
author: pyren451
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I will explore GitHub pages using this site. This description is going to
  appear in the document head meta (for Google search results) and in the
  feed.xml site description.
# social links

github_username:  pyren451

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
